### PR TITLE
added cloud scheduler job to trigger cloud run service

### PR DESCRIPTION
**Pull request by BenGriffith**
not a lot to review. Mainly showing completion of last stage of project/addition of cloud scheduler job/cron job to trigger processing via container.

messages exist in pubsub subscription
Screenshot 2024-05-05 at 6 06 24 PM

cloud scheduler job
Screenshot 2024-05-05 at 6 11 03 PM

container logs showing processing taking place
Screenshot 2024-05-05 at 6 12 06 PM

container logs showing processing completed
Screenshot 2024-05-05 at 6 16 34 PM

records inserted into couple of bigquery tables
Screenshot 2024-05-05 at 6 14 02 PM

Screenshot 2024-05-05 at 6 14 47 PM

### CODE REVIEW

**Comment by bbelderbos** [comment]
Really cool, you should totally write an article about this! ;)

**Comment by BenGriffith** [comment]
Thanks Bob. I'm going to start working on an article.

**Comment by bbelderbos** [comment]
Sweet! Where? Most practical to do it in our Wordpress maybe? I just checked and you did not have an account yet so I made you one. You should have an email to login. When the article goes live also please add a bio, otherwise you don't show up as the author. Let me know when you a draft so I can proofread/review it. Thanks.

**Comment by BenGriffith** [comment]
Thanks for creating an account for me. I will be sure to add a bio along with letting you know when I have a draft complete. Going to start working on it later this week.

**Comment by bbelderbos** [comment]
Great, thanks. I am reading The Rust Programming Language btw 😎

**Pull request merged**
