### PR TITLE
pre-commit, erd, and initial terraform script

### PR DESCRIPTION
**Pull request by BenGriffith**

### CODE REVIEW

**Comment by bbelderbos** [comment]
This looks good, any questions or things for me to check specifically?

**Comment by BenGriffith** [comment]
I added pip-tools/pip-compile to the pre-commit, do you think it's worthwhile or is that overkill?

**Comment by bbelderbos** [comment]
Might be overkill but good point: if you add a requirement to .in you need that recompile step so I can see how you want to automate / streamline that.

**Comment by bbelderbos** [comment]
Also some things to keep into account with this:

image

**Comment by BenGriffith** [comment]
those are good considerations. I think I'm going to remove it.

**Pull request merged**
