### PR TITLE
moving reviewed changes from develop to main

### PR DESCRIPTION
**Pull request by BenGriffith**

### CODE REVIEW

**Comment by bbelderbos** [comment]
For some reason I see the last diff as last time, maybe because it's dev->master pr where last time it was branch->dev? Anything additional to review for me?

**Comment by BenGriffith** [comment]
that's right. Nothing for you to review right now. Testing final changes right now. Planning for PR later this week or early next week.

**Comment by bbelderbos** [comment]
ok sounds good, did you ever tell me what came out the previous check in with Christo regarding this project, you did check in with him no?

**Comment by BenGriffith** [comment]
no, haven't had check in. Last time, I used a calendar link to schedule meeting but couldn't find it this time around so shot him an email, but didn't hear back/I forgot to follow up.

**Comment by bbelderbos** [comment]
ok you still have some outstanding data questions right? then maybe good to email him yes ...

**Comment by BenGriffith** [comment]
I think I'm good now. I was a little uncertain about the architecture when I started on the cloud run component but recalling some of what Christo had said and working through it I think generally/directionally I got it.

**Comment by bbelderbos** [comment]
Happy you got his advice, we can also look at this on our next call.

**Pull request merged**
